Formularz/Models/Dane.cs
using System.ComponentModel.DataAnnotations;
namespace Formularz.Models
{
    public class Dane
    {
        public int Id {  get; set; }

        [Required(ErrorMessage = "Podaj Imię")]
        [MinLength(2, ErrorMessage = "Imię musi mieć co najmniej 2 znaki")]
        public string Imie { get; set; }

        [Required(ErrorMessage ="Podaj Nazwisko")]
        [MinLength(2, ErrorMessage = "Nazwisko musi mieć co najmniej 2 znaki")]
        public string Nazwisko { get; set; }

        [Required(ErrorMessage = "Podaj Email")]
        [EmailAddress(ErrorMessage = "Podaj poprawny adres e-mail")]
        [RegularExpression(".+\\@.+\\.[a-z]{2,3}")]
        public string Email { get; set; }

        [Required(ErrorMessage ="Podaj Hasło")]
        [MinLength(8, ErrorMessage ="Hasło musi mieć co najmniej 8 znaków")]
        [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).+$", ErrorMessage = "Hasło musi zawierać co najmniej jedną cyfrę, jedną dużą literę i jedną małą literę")]

        public string Haslo {  get; set; }

        [Required( ErrorMessage ="Potwierdź Hasło")]
        [DataType(DataType.Password)]
        [Compare("Haslo", ErrorMessage ="Hasła nie są takie same!")]
        public string PotwierdzenieHasla { get; set; }

        [Phone( ErrorMessage ="Podaj poprawny numer telefonu")]
        public string NumerTelefonu { get; set; }

        [Range(10,80, ErrorMessage ="Podaj wiek od 10 do 80")]
        public int? Wiek {  get; set; }

        [Required( ErrorMessage="Wybierz miasto")]
        public string Kategoria { get; set; } 
        public enum Kategorie
        {
             Stuttgart = 1,
             Triest = 2,
             Bucharest = 3,
             Izmir = 4,
             Copenhagen = 5

        }
    }
}

Formularz/Models/ErrorViewModel.cs
namespace Formularz.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Formularz/Controllers/DaneController.cs
using Formularz.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Formularz.Controllers
{
    public class DaneController : Controller
    {
        // GET: DaneController
        public ActionResult Index()
        {
            return View();
        }

        // GET: DaneController/Details/5

        [HttpGet]
        public IActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Form(Dane dane)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Message = "Rejestracja zakończona pomyślnie";
                return View("Wynik", dane);
            }
            else return View();

        }
        public IActionResult Wynik(Dane dane)
        {

            return View(dane);
        }

    }
}

Formularz/Controllers/HomeController.cs
using Formularz.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Formularz.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Formularz/Views/Dane/Form.cshtml
@model Formularz.Models.Dane

@using (Html.BeginForm("Form", "Dane", FormMethod.Post))
{
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <p> Twoje Imię:
        @Html.TextBoxFor(a => a.Imie, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Imie, "", new { @class = "text-danger" })
    </p>
    <p> Twoje Nazwisko:
        @Html.TextBoxFor(a => a.Nazwisko, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Nazwisko, "", new { @class = "text-danger" })
    </p>
    <p> Twój Email:
        @Html.TextBoxFor(a => a.Email, new { @class = "form-control", type = "email" })
        @Html.ValidationMessageFor(a => a.Email, "", new { @class = "text-danger" })
    </p>
    <p> Hasło:
        @Html.PasswordFor(a => a.Haslo, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Haslo, "", new { @class = "text-danger" })
    </p>
    <p> Potwierdzenie Hasła:
        @Html.PasswordFor(a => a.PotwierdzenieHasla, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.PotwierdzenieHasla, "", new { @class = "text-danger" })
    </p>
    <p> Numer Telefonu:
        @Html.TextBoxFor(a => a.NumerTelefonu, new { @class = "form-control", type = "tel" })
        @Html.ValidationMessageFor(a => a.NumerTelefonu, "", new { @class = "text-danger" })
    </p>
    <p> Wiek:
        @Html.TextBoxFor(a => a.Wiek, new { @class = "form-control", type = "number" })
        @Html.ValidationMessageFor(a => a.Wiek, "", new { @class = "text-danger" })
    </p>
    <p> Miasto:
        @Html.DropDownListFor(a => a.Kategoria, Html.GetEnumSelectList<Dane.Kategorie>(), "Wybierz miasto", new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Kategoria, "", new { @class = "text-danger" })
    </p>
    <p>
        <button type="submit" class="btn btn-primary">Zarejestruj się</button>
    </p>
}

Formularz/Views/Dane/Wynik.cshtml
@model Formularz.Models.Dane
@{
    ViewData["Title"] = "Wynik";
}

<h1>@ViewBag.Message</h1>

<p>Imię: @Model.Imie</p>
<p>Nazwisko: @Model.Nazwisko</p>
<p>Email: @Model.Email</p>
<p>Numer Telefonu: @Model.NumerTelefonu</p>
<p>Wiek: @Model.Wiek</p>
<p>Miasto: @Model.Kategoria</p>

Formularz/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Formularz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formularz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Formularz.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Formularz</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dane" asp-action="Form">Formularz</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Formularz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script> @* 1 *@ 
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script> @* 2 *@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>